### ISSUE TITLE
Can't view device data from TagoCore through a dashboard on TagoIO

### ISSUE THREAD

**Issue by requeijaum** [tago-io/tcore#10]
Can't view device data from TagoCore (v0.4.x) through a dashboard on TagoIO.

I'm accessing my TagoIO dashboard inside the same network as the Core (RPi 4B arm64).

When creating a new display and selecting it's data source: the Core can be selected but it does not list it's devices.

![Screenshot_20220723_141247](https://user-images.githubusercontent.com/5564635/180615776-ee6cec52-a526-494e-954d-6980bda90de2.png)

![image](https://user-images.githubusercontent.com/5564635/180615795-5558131e-c87c-4a55-bae7-182e22f1e90a.png)

**Comment by matheuslbenachio** [comment]
Hi there @requeijaum
first of all, thank you for taking the time to write this.

The dashboard visualization for TagoCore data is only available on the latest version of TagoCore (0.5.0). You can download it here: https://downloads.tagocore.com/v0.5.0

**Comment by requeijaum** [comment]
Can I update my TagoCore instance without any hassle? I will backup the MySQL database in any case.

**Comment by matheuslbenachio** [comment]
@requeijaum Yeah, the update should be pretty straightforward. You will need to define a master password and an account to log into TagoCore, but aside from that it should work normally as it does today

**Comment by matheuslbenachio** [comment]
@requeijaum I'm going to go ahead and close this issue, let me know if the update worked for you. If not, feel free to open another issue.
