### ISSUE TITLE
List page send negative amount to pagination

### ISSUE THREAD

**Issue by RicardoStoklosa** [tago-io/tcore#13]
When the window is small, the front send negative amount to api pagination

How to reproduce:
go to device list > resize browser window > refresh page

<img width="538" alt="image(1)" src="https://user-images.githubusercontent.com/16613742/181367285-7929c84b-53ec-48f6-bd06-b5c4ca224964.png">

**Comment by matheuslbenachio** [comment]
@RicardoStoklosa This PR should fix this issue #16
