### ISSUE TITLE
TagoCore can't switch account on Tago.io Integration page

### ISSUE THREAD

**Issue by requeijaum** [tago-io/tcore#26]
I need to remake all my dashboard screens to a new organization granted in my personal Tago.io account. But I can't clear or redo the integration steps for this.

Is there any file or database entry that I can modify to fix this?
I couldn't find anything useful.

![image](https://user-images.githubusercontent.com/5564635/189441569-191aea85-e6ff-4507-bd33-12974d64f4a9.png)

**Comment by requeijaum** [comment]
![image](https://user-images.githubusercontent.com/5564635/189540300-19f1e053-ec1e-4955-9cc1-6f215e981a91.png)
![image](https://user-images.githubusercontent.com/5564635/189540303-c7a997a5-3187-4424-84d8-bd1fe1046e98.png)
![image](https://user-images.githubusercontent.com/5564635/189540306-d7815f03-3d28-479b-8f6a-c98c100e87b9.png)


I found Tago.io Integration Plugin's files and database entries.
Tried deleting them but I still can't reset my integration.

I also tried a factory reset and used a different database plugin. 
Still no success.

**Comment by matheuslbenachio** [comment]
Hey @requeijaum, that's very weird. It seems like requests to the `8999` port aren't working properly. Based on your console it's showing there is a `CORS` error and a `NS_ERROR_DOM_BAD_URI` error.

Are you running TagoCore in a docker container? if so, have you published port 8999 using `-p` or `--publish`?

If you aren't running TagoCore in a docker container, are you able to enable the integration by executing TagoCore on your localhost? (running TagoCore on http://localhost:8888).

Let me know, we'll get this sorted out for you.

**Comment by requeijaum** [comment]
It seems that was a firewall issue. I didn't remember that integration's TCP port was different from the web interface.

I tried allowing TCP 8999 on ufw and seems to be working for now.

![image](https://user-images.githubusercontent.com/5564635/189698059-823b01b3-ecb3-457e-8956-13c606e3600d.png)

**Comment by requeijaum** [comment]
Display data on dashboards seems fine too.

![image](https://user-images.githubusercontent.com/5564635/189704892-29600dbb-814d-4bdb-a932-4e33d04b8e89.png)

**Comment by matheuslbenachio** [comment]
Nice, glad to hear it.

Closing the issue.
