### ISSUE TITLE
Error when change service port

### ISSUE THREAD

**Issue by douglaszuqueto** [tago-io/tcore#32]
Hi guys,

When I try to change the service port and save, the updates form blocks me saying that the field is required.

I need to enable updates and then choose an option to be able to save the port change.

![Console error](https://user-images.githubusercontent.com/7410247/193032126-7a6431f7-af7f-4c16-ba32-1d9021543869.png)

**Comment by matheuslbenachio** [comment]
Hey @douglaszuqueto, that's very odd.
I'm going to look into that for the next release.

**Comment by matheuslbenachio** [comment]
Hey @douglaszuqueto, version 0.7.0 of TagoCore should fix this.

I'll close the issue for now, feel free to open another one if the error is still happening.

**Comment by douglaszuqueto** [comment]
Thanks @matheuslbenachio . The problem was fixed in V0.7.0 :)
