### ISSUE TITLE
Cannot find the last version of tagocore-sdk

### ISSUE THREAD

**Issue by douglaszuqueto** [tago-io/tcore#34]
Hi guys,

I'm developing a plugin and I couldn't find the latest version of the tagocore-sdk library.

The current version of tagocore-sdk on NPM, is v0.6.0.

https://www.npmjs.com/package/@tago-io/tcore-sdk

**Comment by matheuslbenachio** [comment]
Hey @douglaszuqueto, that's fine, v0.6.0 will work normally since there weren't breaking changes between the versions.

We are doing the final tests for the v0.7.0 which will be released very soon with the ability to automatically publish plugins.
