### ISSUE TITLE
Problem with MQTT Plugin

### ISSUE THREAD

**Issue by alexesto** [tago-io/tcore#38]
Hi,

I intalled MQTT Broker Plugin to recieve data from Khomp ITG200, but after create Action with MQTT Trigger the MQTT Plugin stoped e show bellow message. The port 1883 was closeded
You can help me ?

What did I do:
1. Uninstal plugin MQTT 0.7.1
2. Install plugin MQTT 0.7.2
3. Restart server TagoCore
4. Remove Action
5. Insert new Action with same type "MQTT ActionType-Store Data"

Plugin Log is:
[19:25:41.150]: Setting up MQTT without certificate
[19:25:41.151]: Port=1883 Service=MQTT
[19:25:43.697]: Device connected [61418feb821bab80139038df]

Thank's

Alex

![1665507638434011_661881388](https://user-images.githubusercontent.com/12516790/196753803-b90bedd9-a2e1-4cf2-b5a7-44472cf0975f.png)

**Comment by douglaszuqueto** [comment]
Hi @alexesto ,

I have the same error here.

From the debug I did, the plugin breaks when the decoder is invalid.

Can you test the decoder example below to see if it is normal as it was here?

```js
console.log(payload);

payload = [];
```

The expected output is:

![Screenshot](https://user-images.githubusercontent.com/7410247/196769500-3bbbd4fb-1be2-4f47-b3bb-dabda9e2807c.png)

**Another decoder test:**

```js
console.log(payload);

payload = [];

const counter = payload.find((item) => item.n === "uplink");

if (counter) {
  payload.push({
    variable: "counter",
    value: counter.v,
  });
}
```

For example, this decoder save uplink counter in the bucket.

**Comment by douglaszuqueto** [comment]
Exemple of decoder to parse SenML payload format to TagoCore format:

```js
const measurements = payload.filter((x) => x.n);

payload = measurements.map((d) => {
  return {
    variable: String(d.n).replace(/:/, ""),
    value: d.v || d.vs || d.vb,
  };
});
``` 
Output:

![Screenshot from 2022-10-19 15-17-23](https://user-images.githubusercontent.com/7410247/196772446-543b2d8e-2e3d-49f5-97cc-1cfd71e9793f.png)

Context:

* Gateway ITG200
* Device NIT20LI

**Comment by RicardoStoklosa** [comment]
Hi @alexesto, good to know that your problem was solved.
Thx @douglaszuqueto for the help.
This issue was added to our pipeline
