### ISSUE TITLE
Issue with TTN Plugin

### ISSUE THREAD

**Issue by GTsapparellas** [tago-io/tcore#42]
The guide for setting up TTN on tago core doesn't seem to work.

That's the response we're getting:

![image](https://user-images.githubusercontent.com/20886809/197978688-cd902a1f-4c5f-45f0-9bda-a6e84b0479a4.png)

That's the webhook set-up:

![image](https://user-images.githubusercontent.com/20886809/197979158-bd32199c-db46-4896-97aa-a333955b561b.png)

Anything that doesn't seem right?

**Comment by vitorfdl** [comment]
hey @GTsapparellas ,
Is TTN server on promise and running in your machine ? If not, I don't think providing localhost as URL would work at all.

localhost only works when you're performing requests from your own machine. For TTN, you need to provide your IP address or DNS. In some cases, you will also need to make sure you have your ports open in your router.

**Comment by RicardoStoklosa** [comment]
Hi @GTsapparellas, hope this solve your problem!
I will be closing this issue for now
