### ISSUE TITLE
Add support for device params in payload parser context.

### ISSUE THREAD

**Issue by douglaszuqueto** [tago-io/tcore#6]
Add support for device params in payload parser context.

```js
const context = vm.createContext({
  payload,
  raw_payload: options?.rawPayload,
  dayjs,
  device: {
    id: device.id,
    tags: device.tags,
    params: [], // here
  },
  console: {
    log: (...args: any[]) => onLog(device, args, options),
    debug: (...args: any[]) => onLog(device, args, options),
    error: (...args: any[]) => onLog(device, args, options),
  },
});
```
* [Source code](https://github.com/tago-io/tcore/blob/main/packages/tcore-api/src/Services/PayloadParserCodeExecution.ts#L44)

**Comment by matheuslbenachio** [comment]
Hey @douglaszuqueto, thanks for engaging!

This feels like a good improvement, seems like it's something easy to do and it add value.

**Comment by matheuslbenachio** [comment]
I just realized that this is actually a bug, not a feature request. The params key is already being passed to the device but it's always empty.

@douglaszuqueto #8 should fix the issue.

**Comment by douglaszuqueto** [comment]
It depends on the point of view, but it can be seen as a bug, hehe.

I thought that because of the beginning of the project, the parameters could be "disabled" for some reason.

Thank you very much @matheuslbenachio

**Comment by matheuslbenachio** [comment]
@douglaszuqueto Oh ok, that makes sense.

And no problem, I actually should be the one thanking you since you brought this to our attention!

The PR should be merged soon and should be available in the next version of the application.
